# Generated by Django 5.2.4 on 2025-08-02 15:42

from django.db import migrations

def set_default_user(apps, schema_editor):
    Note = apps.get_model('api', 'Note')
    Note.objects.filter(user__isnull=True).update(user_id=1)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note_user'),
    ]

    operations = [
        migrations.RunPython(set_default_user),
    ]
